In [7]:
import pandas as pd

# Load JSON
data = pd.read_json('delhi_metro_trips.json')

data

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27.0,None,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23.0,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,RAJIV CHOWK,Shivaji Park,12.77,67.29,15.91,21.0,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20.0,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22.0,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18.0,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20.0,Single,off-peak

In [9]:
# Removing extra spaces in station names
# Standardizing station naming conventions

data['From_Station'] = data['From_Station'].str.strip()
data['To_Station'] = data['To_Station'].str.strip()

data

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27,None,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,RAJIV CHOWK,Shivaji Park,12.77,67.29,15.91,21,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20,Single,off-peak

In [11]:
# Handling missing values in ticket types

data['Ticket_Type'] = data['Ticket_Type'].fillna('Unknown')
data['Remarks'] = data['Remarks'].fillna('No Remarks')

data

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,RAJIV CHOWK,Shivaji Park,12.77,67.29,15.91,21,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20,Single,off-peak

In [12]:
# Converting date columns into datetime format

data['Date'] = pd.to_datetime(data['Date'])

data

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,RAJIV CHOWK,Shivaji Park,12.77,67.29,15.91,21,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20,Single,off-peak

In [13]:
# Ensuring numeric columns are correctly formatted

data['Distance_km'] = data['Distance_km'].astype(float)
data['Fare'] = data['Fare'].astype(float)
data['Cost_per_passenger'] = data['Cost_per_passenger'].astype(float)
data['Passengers'] = data['Passengers'].fillna(0).astype(int)

data

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,RAJIV CHOWK,Shivaji Park,12.77,67.29,15.91,21,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20,Single,off-peak

In [14]:
# Save cleaned data
data.to_csv('metro_data.csv', index=False)